

POLYGON_MODE_POINT = 0
POLYGON_MODE_LINE = 1
POLYGON_MODE_SOLID = 2


-- for gh_renderer.rasterizer_set_cull_face()
--
POLYGON_FACE_NONE = 0
POLYGON_FACE_BACK = 1
POLYGON_FACE_FRONT = 2
POLYGON_FACE_BACK_FRONT = 3



PRIMITIVE_TRIANGLE = 0
PRIMITIVE_TRIANGLE_STRIP = 1
PRIMITIVE_LINE = 2
PRIMITIVE_LINE_STRIP = 3
PRIMITIVE_LINE_LOOP = 4
PRIMITIVE_LINE_ADJACENCY = 5
PRIMITIVE_LINE_STRIP_ADJACENCY = 6
PRIMITIVE_PATCH = 7
PRIMITIVE_POINT = 8



-- for gh_texture.set_sampler_params()
--
SAMPLER_FILTERING_NEAREST = 1
SAMPLER_FILTERING_LINEAR = 2
SAMPLER_FILTERING_TRILINEAR = 3

SAMPLER_ADDRESSING_WRAP = 1
SAMPLER_ADDRESSING_CLAMP_TO_EDGE = 2
SAMPLER_ADDRESSING_MIRROR = 3
SAMPLER_ADDRESSING_CLAMP_TO_BORDER = 4




-- GPU program - shader type for GPU program creation.
--
GPU_SHADER_VERTEX = 0
GPU_SHADER_PIXEL = 1
GPU_SHADER_GEOMETRY = 2
GPU_SHADER_TESS_CONTROL = 3
GPU_SHADER_TESS_EVAL = 4
GPU_SHADER_COMPUTE = 5
GPU_SHADER_MESH_NV = 6
GPU_SHADER_TASK_NV = 7


-- blending factors
-- for gh_renderer.set_blending_factors()
--
BLEND_FACTOR_ONE = 1
BLEND_FACTOR_SRC_ALPHA = 2
BLEND_FACTOR_ONE_MINUS_DST_ALPHA = 3
BLEND_FACTOR_ONE_MINUS_DST_COLOR = 4
BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = 5
BLEND_FACTOR_DST_COLOR = 6
BLEND_FACTOR_DST_ALPHA = 7
BLEND_FACTOR_SRC_COLOR = 8
BLEND_FACTOR_ONE_MINUS_SRC_COLOR = 9



-- Depth test 
-- for gh_renderer.set_depth_test_func()
--
RENDERER_CMP_FUNC_NEVER = 0
RENDERER_CMP_FUNC_LESS = 1
RENDERER_CMP_FUNC_LESS_OR_EQUAL = 2
RENDERER_CMP_FUNC_GREATER = 3
RENDERER_CMP_FUNC_GREATER_OR_EQUAL = 4
RENDERER_CMP_FUNC_EQUAL = 5
RENDERER_CMP_FUNC_NOT_EQUAL = 6
RENDERER_CMP_FUNC_ALWAYS = 7
